#!/bin/bash
#
# Author: Alejandro Sanchez Acosta
#
# Copyright (c) 2018 Adobe Systems Incorporated. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source "${BASH_SOURCE%/*}/configsqs"

QUEUE=https://sqs.eu-west-1.amazonaws.com/258057316678/splunkevents
REGION=eu-west-1

JSON=$(aws sqs receive-message --queue-url ${QUEUE} --attribute-names All --message-attribute-names All --max-number-of-messages 10 --region eu-west-1)

RECEIPT=$(cat $JSON | jq .Messasges[] | jq -r .ReceiptHandle)
PAYLOAD=$(cat $JSON | jq .Messasges[] | jq -r .Body)

aws sqs delete-message --queue-url ${QUEUE} --receipt-handle "${RECEIPT}" --region ${REGION}
