#!/bin/bash
#
# Author: Alejandro Sanchez Acosta
#
# Copyright (c) 2018 Adobe Systems Incorporated. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source configdd

START=$(date +%s)
END=$(date -v -10M +%s)

data=$(curl -s -G -H "Content-type: application/json" \
    -d "start=${END}" \
    -d "end=${START}" \
    -d "sources=${SOURCE}" \
    -d "api_key=${APIKEY}" \
    -d "application_key=${APPKEY}" \
    'https://app.datadoghq.com/api/v1/events')

HOSTS=$(echo $data | grep -v %%% | grep -v Splunk | grep -v "\- \- \-" | grep -v "\`\`\`" | tr -d '\' | jq -r '.search_name, .result' | tr -d '
{' | sed 's/}/\
/g' | uniq | awk 'NF' | tr -d '"' | sed 's/  count/, count/g')

# echo $HOSTS
# #
# for i in $(echo $HOSTS)
# do
ALERT=$(echo $HOSTS | cut -d "," -f1)
HOST=$(echo $HOSTS | cut -d "," -f6 | cut -d "," -f2)
SERVER=$(echo $HOSTS  | cut -d "," -f3 | cut -d "host" -f 1)
echo "../actions/run_actions -n '$ALERT' -p HOST=$HOST -p SERVER=$SERVER"
# done
#
# COUNTER=0
# for HOST in $HOSTS
# do
#   echo $HOST
# done
